### ISSUE TITLE
p2p discover use leveldb instead of rocksdb

### ISSUE THREAD

**Issue by 516108736** [QuarkChain/goquarkchain#194]

**Comment by lazaridiscom** [comment]
Provide a description (e.g. rationales etc.), and the team should assess if this is something that will be done in near future.

Otherwise close.

**Comment by pingke** [comment]
Done commit (https://github.com/QuarkChain/goquarkchain/commit/c8a7ef3f70e30ae269e55cf77d6dc9f2706f2c71)
