### ISSUE TITLE
sendRawTransaction error from web3js

### ISSUE THREAD

**Issue by syntrust** [QuarkChain/goquarkchain#400]
run [web3 example ](https://gist.github.com/qcgg/1ab0352c5b2299270b5795648cca83d8), if providing fullshardkey like '0x00010000', got error 'invalid argument 1: json: cannot unmarshal hex number with leading zero digits into Go value of type hexutil.Uint'. 
if remove leading zeros, got  error: { code: -32000, message: 'len is 4 should 5' } }

**Comment by tomdong2010** [comment]
fixed
