### ISSUE TITLE
Chain sync failed

### ISSUE THREAD

**Issue by frode88** [QuarkChain/goquarkchain#452]
Hei.
Cluster just stop working after block 146682

![Skjermbilde](https://user-images.githubusercontent.com/22121200/68105400-ae2eac80-fede-11e9-9e1b-757407a8aab0.PNG)

**Comment by frode88** [comment]
invalid argument 0: json: cannot unmarshal hex number with leading zero digits into Go value of type hexutil.Uint

and this everytime try to get work from rpc

**Comment by frode88** [comment]
Hi Again.
Look like slave2 have issue.

![Skjermbilde](https://user-images.githubusercontent.com/22121200/68273200-13f97080-0066-11ea-9a51-8a7cd9ab8fdb.PNG)

**Comment by tomdong2010** [comment]
> invalid argument 0: json: cannot unmarshal hex number with leading zero digits into Go value of type hexutil.Uint
> 
> and this everytime try to get work from rpc



> invalid argument 0: json: cannot unmarshal hex number with leading zero digits into Go value of type hexutil.Uint
> 
> and this everytime try to get work from rpc

**Comment by tomdong2010** [comment]
i`ve fixed the issue that is same as it , you can try again

**Comment by frode88** [comment]
@tomdong2010 That chain stop synec? I did pull last change like 20 min ago and tried and its the same issue.

**Comment by tomdong2010** [comment]
@frode88    i just commited it  , after tomorrow, you can try it

**Comment by tomdong2010** [comment]
@frode88 it need to review

**Comment by frode88** [comment]
@tomdong2010 Thank you. I will try it when it done and I will give you feedback. You probley mean this one (fix issue 430 400)

**Comment by frode88** [comment]
json: cannot unmarshal hex string without 0x prefix into Go value of type hexutil.Uint. Is the params to getwork are the same as python?

**Comment by frode88** [comment]
@tomdong2010  Hi.Any good news?

**Comment by pingke** [comment]
the slave failure "Too many open files", is cause by too many rocksDB files has been open, you need to increase the limitation by the following command:
ulimit -HSn 102400

you can also add that command to /etc/profile

**Comment by frode88** [comment]
dosent work but i found how to solve this issue. thank you.
