### ISSUE TITLE
QuarkChain go implementation is in stable for running a node?

### ISSUE THREAD

**Issue by MegaSolar** [QuarkChain/goquarkchain#458]
Hello. 

I wonder that quarkchain go implementation is stable for running a node. 
someone would give me for comment about this would be appreciated.

**Comment by pingke** [comment]
yes, we have a node which has joined mainnet for about two weeks.

**Comment by MegaSolar** [comment]
@pingke Cool . 
I will running a node through golang implementation as soon as possible. 
thanks for comment.

**Comment by frode88** [comment]
@MegaSolar Hi. Tell me if sync work. Trying for days now.

**Comment by pingke** [comment]
if you put all the slave in the same machine, you may meet "Too many open files" issue, which is cause by too many rocksDB files has been open, you need to increase the limitation by the following command:
ulimit -HSn 102400
you can also add that command to /etc/profile

**Comment by MegaSolar** [comment]
@frode88 Hi. now I'm trying to set up node by myself. 
but I met some issues about it, so I published issues @ #472 . 
if you knew about this, please comment.

**Comment by MegaSolar** [comment]
@pingke TUSM. I suggest you please see #472. 
I'm a bit in struggle to handle it.

**Comment by pingke** [comment]
I sow you found the solution, will close this issue. and welcome to create any issue to us for your problems or questions.
