### ISSUE TITLE
Make a Download link of snapshots of the chain

### ISSUE THREAD

**Issue by frode88** [QuarkChain/goquarkchain#462]
Hi.
Can you make a link to download the chain same as python  cluster have?

thank you.

**Comment by pingke** [comment]
ok, we are preparing this, and will info you when it is done.

**Comment by frode88** [comment]
@pingke Thank you. Hope it go fast, have big issue Syncing the cluster.

**Comment by frode88** [comment]
Hi. will you share link with us? thank you
