### ISSUE TITLE
Slave just die.

### ISSUE THREAD

**Issue by frode88** [QuarkChain/goquarkchain#485]
![slave](https://user-images.githubusercontent.com/22121200/68928604-bf9f7080-078a-11ea-827d-5543bdc5d391.PNG)

**Comment by frode88** [comment]
and cluster say wrong mixdigit... havnt done anychange. same code used on python cluster

**Comment by frode88** [comment]
![Skjermbilde](https://user-images.githubusercontent.com/22121200/68953610-8aaf1000-07c2-11ea-99cd-cd40a4255438.PNG)

**Comment by pingke** [comment]
we will take a look at it. would you share the config you use to rum?

**Comment by frode88** [comment]
Hi.
This one


https://github.com/QuarkChain/goquarkchain/blob/master/mainnet/singularity/cluster_config_template.json

**Comment by frode88** [comment]
just gave up on this go cluster:) GL guys

**Comment by pingke** [comment]
issue has been fix， please try again

**Comment by frode88** [comment]
do you have link of snapshot of the chain? because i deleted the node and take 2 days to download the chain.

**Comment by syntrust** [comment]
try this: curl https://qkcmainnet-go.s3.amazonaws.com/data/`curl https://qkcmainnet-go.s3.amazonaws.com/data/LATEST`.tar.gz --output data.tar.gz
