### ISSUE TITLE
compile issue: undefined function in consensus/qkchash/native/wrapper.go

### ISSUE THREAD

**Issue by ccyanxyz** [QuarkChain/goquarkchain#494]
Centos 7
go 1.12.10
swig 4.0.1

Follow the build instructions in readme, all working fine until `go test ./...`:
```
-bash-4.2$ go test ./...
# github.com/QuarkChain/goquarkchain/consensus/qkchash/native
consensus/qkchash/native/wrapper.go:17:17: undefined: Cache_create
consensus/qkchash/native/wrapper.go:21:4: undefined: Cache_destroy
consensus/qkchash/native/wrapper.go:34:2: undefined: Qkc_hash
consensus/qkchash/native/wrapper.go:44:2: undefined: Qkc_hash_with_rotation_stats
go build github.com/ethereum/go-ethereum/crypto/secp256k1: build constraints exclude all Go files in /home/cyan/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.20/crypto/secp256k1
# github.com/QuarkChain/goquarkchain/serialize [github.com/QuarkChain/goquarkchain/serialize.test]
serialize/deserializer_test.go:58:59: constant 361700864190383365 overflows uint
# github.com/QuarkChain/goquarkchain/qkcdb
qkcdb/database.go:19:14: undefined: gorocksdb.DB
qkcdb/database.go:20:14: undefined: gorocksdb.ReadOptions
qkcdb/database.go:21:14: undefined: gorocksdb.WriteOptions
...
```
in `go/src/github.com/QuarkChain/goquarkchain/consensus/qkchash/native`:
```
-bash-4.2$ ls
libqkchash.so  native.i         qkchash.h       wrapper_test.go
Makefile       native_wrap.cxx  qkchash_llrb.h
native_gc.c    native_wrap.o    util.h
native.go      qkchash.cpp      wrapper.go
```

try to build `cluster`:
```
-bash-4.2$ ls
config.go  config_test.json  main.go  usage.go
-bash-4.2$ go build
# github.com/QuarkChain/goquarkchain/consensus/qkchash/native
../../consensus/qkchash/native/wrapper.go:17:17: undefined: Cache_create
../../consensus/qkchash/native/wrapper.go:21:4: undefined: Cache_destroy
../../consensus/qkchash/native/wrapper.go:34:2: undefined: Qkc_hash
../../consensus/qkchash/native/wrapper.go:44:2: undefined: Qkc_hash_with_rotation_stats
go build github.com/ethereum/go-ethereum/crypto/secp256k1: build constraints exclude all Go files in /home/cyan/go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.20/crypto/secp256k1
# github.com/QuarkChain/goquarkchain/qkcdb
../../qkcdb/database.go:19:14: undefined: gorocksdb.DB
../../qkcdb/database.go:20:14: undefined: gorocksdb.ReadOptions
../../qkcdb/database.go:21:14: undefined: gorocksdb.WriteOptions
```

**Comment by pingke** [comment]
we are looking at it

**Comment by pingke** [comment]
@mask-pp please take a look at it.

**Comment by pingke** [comment]
Hi, as we do not go through all the steps in Centos, I suggest you use ubumtu to run all this.
we will Centos readme later, as install RocksDB and some other dependencies is different, I suggest you to look at https://www.jianshu.com/p/f233528c8303. https://www.cnblogs.com/dongc/p/6896850.html to install those dependencies

**Comment by ccyanxyz** [comment]
OK, thanks.

**Comment by mask-pp** [comment]
gcc -v >=7.4.0:
	wget http://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.gz
	tar -xvzf gcc-7.4.0.tar.gz
	cd gcc-7.4.0 && ./contrib/download_prerequisites
	mkdir -p build_gcc_4.8.1 && cd &_
	../gcc-7.4.0/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib && make && make install

rocksdb:
	yum install -y snappy snappy-devel zlib zlib-devel bzip2 bzip2-devel lz4-devel libasan
	git clone -b v6.1.2 https://github.com/facebook/rocksdb.git
	sudo make shared_lib
	sudo make install-shared
	
qkchash && make cluster:
	cd $GOPATH/src/github.com/QuarkChain/goquarkchain/consensus/qkchash/native/ && g++ -shared -o libqkchash.so -fPIC qkchash.cpp -O3 -std=gnu++11
	cd ../../../cmd/cluster && go build -v

**Comment by mask-pp** [comment]
~& ./cluster (get error like that please reference [)](https://blog.csdn.net/ZX714311728/article/details/69628836)
/usr/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./destructor)

**Comment by mask-pp** [comment]
~& ./cluster (get error like that please reference [here](https://blog.csdn.net/ZX714311728/article/details/69628836)
/usr/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./destructor)

**Comment by mask-pp** [comment]
~& ./cluster (get error like that please reference [helpful link](https://blog.csdn.net/ZX714311728/article/details/69628836))
/usr/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./destructor)

**Comment by ccyanxyz** [comment]
I've fixed it. Thanks for the help.

A note for those who run into this problem:
when run `go build -v` to build cluster:
```
-bash-4.2$ go build -v
github.com/QuarkChain/goquarkchain/consensus/qkchash/native
# github.com/QuarkChain/goquarkchain/consensus/qkchash/native
native_gc.c:14:10: fatal error: runtime.h: No such file or directory
 #include "runtime.h"
          ^~~~~~~~~~~
compilation terminated.
```
`native_gc.c` is generated because I ran `swig` without `-cgo` option once, just delete it and try `go build -v` again.
