### ISSUE TITLE
rpc error: account for tps not ready

### ISSUE THREAD

**Issue by ccyanxyz** [QuarkChain/goquarkchain#507]
I configured the cluster parameters as suggested in the loadtest readme and started mining, but when I try to generate transactions I get the following rpc error:
```
-bash-4.2$ curl -X POST -H 'content-type: application/json' --data '{"jsonrpc": "2.0","method": "createTransactions","params": [{ "numTxPerShard": 10000,"xShardPercent": 0}],"id": 1}' http://127.0.0.1:38491
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rpc error: code = Unknown desc = account for tps not ready"}}
```
I've set my private key in cluster config.

**Comment by syntrust** [comment]
wait until the cluster fully started before create tx, usually with a enode value of itself printed.

**Comment by ccyanxyz** [comment]
Solved. Thanks.
