### ISSUE TITLE
Main network synchronization failed

### ISSUE THREAD

**Issue by zaga01** [QuarkChain/goquarkchain#544]
ERROR[01-03|15:09:46.345] Running sync task failed                 synchronizer=runner error="rpc error: code = Unknown desc = invalid gas used (remote: 44952 local: 42884)"
INFO [01-03|15:09:52.281] Downloading blocks                       synctask=root start-ancestor=363308 t.header=375326 length=500 from=363308 to=363808 t.header=375326
ERROR[01-03|15:09:53.032] Running sync task failed                 synchronizer=runner error="rpc error: code = Unknown desc = invalid gas used (remote: 44952 local: 42884)"
INFO [01-03|15:09:56.833] Downloading blocks                       synctask=root start-ancestor=363308 t.header=375326 length=500 from=363308 to=363808 t.header=375326
ERROR[01-03|15:09:57.167] Running sync task failed                 synchronizer=runner error="rpc error: code = Unknown desc = invalid gas used (remote: 44952 local: 42884)"
INFO [01-03|15:10:02.877] Downloading blocks                       synctask=root start-ancestor=363308 t.header=375326 length=500 from=363308 to=363808 t.header=375326
ERROR[01-03|15:10:03.281] Running sync task failed                 synchronizer=runner error="rpc error: code = Unknown desc = invalid gas used (remote: 44952 local: 42884)"

**Comment by 516108736** [comment]
please update [code](https://github.com/QuarkChain/goquarkchain/commit/ea383a83e097c301187ee0b39bbd51b13f16c12f)

**Comment by 516108736** [comment]
please update [code](https://github.com/QuarkChain/goquarkchain/tree/master)
