### ISSUE TITLE
Fullnode stop syncing without error or warning

### ISSUE THREAD

**Issue by jishankai** [QuarkChain/goquarkchain#561]
I use the newest docker to set up the mainnet fullnode. But after one day, the sync stopped. No error, no warning.

my commands for running cluster:
```
./cluster --cluster_config ../../mainnet/singularity/cluster_config_template.json --ws --ws_port 38590 --service S0 >> s0.log 2>&1 &
./cluster --cluster_config ../../mainnet/singularity/cluster_config_template.json --service S1 >> s1.log 2>&1 &
./cluster --cluster_config ../../mainnet/singularity/cluster_config_template.json --service S2 >> s2.log 2>&1 &
./cluster --cluster_config ../../mainnet/singularity/cluster_config_template.json --service S3 >> s3.log 2>&1 &
./cluster --cluster_config ../../mainnet/singularity/cluster_config_template.json --json_rpc_host 0.0.0.0  >>master.log 2>&1 & 
//./cluster --cluster_config ../../mainnet/singularity/cluster_config_template.json --json_rpc_host 0.0.0.0 --json_rpc_private_host 0.0.0.0 >>master.log 2>&1 & 
```

I was mining shard 6 by using qkchashx1.0 docker image when the fullnode stopped syncing.

**Comment by qizhou** [comment]
Any info of the github commit?

**Comment by skji** [comment]
commit hash: 50dff83ef825cbbcb732fcec1dc7e7c157e6120b

**Comment by qizhou** [comment]
I start a cluster with 1.4.3 and it failed to sync with the following errors:

![image](https://user-images.githubusercontent.com/2541286/83812528-464b7900-a6ee-11ea-98ca-bf5e9109cfff.png)

**Comment by pingke** [comment]
resolved by commit (https://github.com/QuarkChain/goquarkchain/commit/8ec9be69c467eaa3cc68fb18c370c8fce2d86a05)
