### ISSUE TITLE
root chain posw mining submit always false after a period of time

### ISSUE THREAD

**Issue by jishankai** [QuarkChain/goquarkchain#563]
![image](https://user-images.githubusercontent.com/2420990/75846507-85301100-5e17-11ea-937f-c86c16b0b740.png)

![image](https://user-images.githubusercontent.com/2420990/75846496-7e090300-5e17-11ea-8109-f7397b7b6269.png)

**Comment by skji** [comment]
commit hash: 50dff83ef825cbbcb732fcec1dc7e7c157e6120b

**Comment by 516108736** [comment]
暂时先关闭了，跑了一个星期没发现问题 @jishankai
