### ISSUE TITLE
problems when sending RPC call

### ISSUE THREAD

**Issue by wdwd5wd** [QuarkChain/goquarkchain#592]
When I use the goclient to send txs to my local Quarkchain server, sometimes the client will drop following issues:

rpc call getAccountData() on http://13.56.95.27:38391: Post http://13.56.95.27:38391: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x70d005]

goroutine 1 [running]:
github.com/wdwd5wd/AllocationClient/client.(*EvmTransaction).getUnsignedHash(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/wdwd5wd/AllocationClient/client/transaction.go:188 +0x75
github.com/wdwd5wd/AllocationClient/client.SignTx(0x0, 0xc280f53050, 0xc11985d620, 0x1, 0x1)
        /home/ubuntu/go/src/github.com/wdwd5wd/AllocationClient/client/transaction.go:283 +0x49
main.SendMigTx(0xc11985d820, 0xc11985d820, 0x7e9fdf)
        /home/ubuntu/go/src/github.com/wdwd5wd/AllocationClient/main/main.go:1156 +0x4d9
main.AccountMigration(0xc00b8d3f40, 0x32, 0xc00b8d3f80, 0x40, 0xc00b8d3f40, 0x32, 0xc00b8d3f80, 0x40, 0xc0318c7b8b, 0x1, ...)
        /home/ubuntu/go/src/github.com/wdwd5wd/AllocationClient/main/main.go:389 +0x9f0
main.main()
        /home/ubuntu/go/src/github.com/wdwd5wd/AllocationClient/main/main.go:793 +0x1d6d
exit status 2

I assume the problem is produced by the server but I cannot figure out why.

Could anyone help me to solve this issue?

**Comment by 516108736** [comment]
1:根据你说的情况测试了下 https://github.com/QuarkChain/goqkcclient
	流程：
		1.1 启动goquarkchain 
			代码:https://github.com/QuarkChain/goquarkchain/tree/users/chunfengSun/fixTxpoolNetwork.
			config:https://github.com/QuarkChain/goqkcclient/blob/master/sample/cluster_config_template.json
			启动命令:将https://github.com/QuarkChain/goquarkchain/tree/master/mainnet/singularity下的cluster_config_template.json替换成上个config，在cmd/cluster 下执行 ./run_cluster.sh ../../mainnet/singularity/cluster_config_template.json
		1.2 测试goqkcclient
			启动发交易:进入https://github.com/QuarkChain/goqkcclient/sample 执行 go run main.go 可以看到交易发送成功
2:如果你用的不是goqkcclient代码，而是自己写的，请按照上述流程仔细写清楚操作的每一步(包括代码，config，启动命令)

ps:如果比较着急可以加微信15518957281

**Comment by 516108736** [comment]
@wdwd5wd

**Comment by wdwd5wd** [comment]
thanks, already solved.
