### ISSUE TITLE
sync failed at root chain 565804

### ISSUE THREAD

**Issue by pingke** [QuarkChain/goquarkchain#596]
sync failed at root chain 565804.  TX has issue. http://mainnet.quarkchain.io/tx/0x949e6e4af86325126af0010cf653f6e60e676a6e4d14f122d6ede24b8a04a5b90006cfa1
error log see attach 
<img width="843" alt="issue" src="https://user-images.githubusercontent.com/14110556/81628868-5e541380-9434-11ea-8f02-37730738bdef.png">

**Comment by syntrust** [comment]
Caused by: missing increasing nonce when create contract thru deploySystemContract (000000000000000000000000000000514b430003)
