### ISSUE TITLE
automated tests on fixture data

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/goquarkchain#646]
goquarkchain should have automated tests on EVM tests ([fixtures](https://github.com/QuarkChain/goquarkchain/tree/master/tests/testdata))

**Comment by ping-ke** [comment]
already include in daily test

**Comment by ping-ke** [comment]
this test will be run for every check-in. sample: https://github.com/QuarkChain/goquarkchain/runs/4544718684?check_suite_focus=true,  and daily-check,  test case -- TestState under github.com/QuarkChain/goquarkchain/tests
